In [1]:
import pandas as pd

In [3]:
matches = pd.read_csv('matches.csv')

In [4]:
matches.head()

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN

In [5]:
matches.columns

Index(['id', 'season', 'city', 'date', 'team1', 'team2', 'toss_winner',
       'toss_decision', 'result', 'dl_applied', 'winner', 'win_by_runs',
       'win_by_wickets', 'player_of_match', 'venue', 'umpire1', 'umpire2',
       'umpire3'],
      dtype='object')

In [7]:
#no of matches in every season
pd.value_counts(matches['season'], sort=False)

2008    58
2009    57
2010    60
2011    73
2012    74
2013    76
2014    60
2015    59
2016    60
2017    59
2018    60
2019    60
Name: season, dtype: int64

In [8]:
pd.value_counts(matches['season'])

2013    76
2012    74
2011    73
2019    60
2018    60
2016    60
2014    60
2010    60
2017    59
2015    59
2008    58
2009    57
Name: season, dtype: int64

In [9]:
#no of times a team won
pd.value_counts(matches['winner'])

Mumbai Indians                 109
Chennai Super Kings            100
Kolkata Knight Riders           92
Royal Challengers Bangalore     84
Kings XI Punjab                 82
Rajasthan Royals                75
Delhi Daredevils                67
Sunrisers Hyderabad             58
Deccan Chargers                 29
Gujarat Lions                   13
Pune Warriors                   12
Delhi Capitals                  10
Rising Pune Supergiant          10
Kochi Tuskers Kerala             6
Rising Pune Supergiants          5
Name: winner, dtype: int64

In [11]:
#no of times a player was awarded man of match award
pd.value_counts(matches['player_of_match']).head()

CH Gayle          21
AB de Villiers    20
MS Dhoni          17
DA Warner         17
RG Sharma         17
Name: player_of_match, dtype: int64

In [16]:
#find the winner of the ipl seasons
final_matches = matches.drop_duplicates('season', keep='last')

In [17]:
final_matches

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
58,59,2017,Hyderabad,2017-05-21,Mumbai Indians,Rising Pune Supergiant,Mumbai Indians,bat,normal,0,Mumbai Indians,1,0,KH Pandya,"Rajiv Gandhi International Stadium, Uppal",NJ Llong,S Ravi,NaN
116,117,2008,Mumbai,2008-06-01,Chennai Super Kings,Rajasthan Royals,Rajasthan Royals,field,normal,0,Rajasthan Royals,0,3,YK Pathan,Dr DY Patil Sports Academy,BF Bowden,RE Koertzen,NaN
173,174,2009,Johannesburg,2009-05-24,Deccan Chargers,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Deccan Chargers,6,0,A Kumble,New Wanderers Stadium,RE Koertzen,SJA Taufel,NaN
233,234,2010,Mumbai,2010-04-25,Chennai Super Kings,Mumbai Indians,Chennai Super Kings,bat,normal,0,Chennai Super Kings,22,0,SK Raina,Dr DY Patil Sports Academy,RE Koertzen,SJA Taufel,NaN
306,307,2011,Chennai,2011-05-28,Chennai Super Kings,Royal Challengers Bangalore,Chennai Super Kings,bat,normal,0,Chennai Super Kings,58,0,M Vijay,"MA Chidambaram Stadium, Chepauk",Asad Rauf,SJA Taufel,NaN
380,381,2012,Chennai,2012-05-27,Chennai Super Kings,Kolkata Knight Riders,Chennai Super Kings,bat,normal,0,Kolkata Knight Riders,0,5,MS Bisla,"MA Chidambaram Stadium, Chepauk",BF Bowden,SJA Taufel,NaN
456,457,2013,Kolkata,2013-05-26,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,normal,0,Mumbai Indians,23,0,KA Pollard,Eden Gardens,HDPK Dharmasena,SJA Taufel,NaN
516,517,2014,Bangalore,2014-06-01,Kings XI Punjab,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,3,MK Pandey,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN
575,576,2015,Kolkata,2015-05-24,Mumbai Indians,Chennai Super Kings,Chennai Super Kings,field,normal,0,Mumbai Indians,41,0,RG Sharma,Eden Gardens,HDPK Dharmasena,RK Illingworth,NaN
635,636,2016,Bangalore,2016-05-29,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN
695,7953,2018,Mumbai,27/05/18,Sunrisers Hyderabad,Chennai Super Kings,Chennai Super Kings,field,normal,0,Chennai Super Kings,0,8,SR Watson,Wankhede Stadium,Marais Erasmus,S Ravi,Nitin Menon
755,11415,2019,Hyderabad,12/05/19,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,normal,0,Mumbai Indians,1,0,JJ Bumrah,Rajiv Gandhi Intl. Cricket Stadium,Nitin Menon,Ian Gould,Nigel Llong

In [18]:
pd.value_counts(final_matches['winner'])

Mumbai Indians           4
Chennai Super Kings      3
Kolkata Knight Riders    2
Rajasthan Royals         1
Deccan Chargers          1
Sunrisers Hyderabad      1
Name: winner, dtype: int64

In [31]:
#find winner of every season
temp_df = final_matches.reset_index()

In [32]:
temp_df[['season','winner']]

    season                 winner
0     2017         Mumbai Indians
1     2008       Rajasthan Royals
2     2009        Deccan Chargers
3     2010    Chennai Super Kings
4     2011    Chennai Super Kings
5     2012  Kolkata Knight Riders
6     2013         Mumbai Indians
7     2014  Kolkata Knight Riders
8     2015         Mumbai Indians
9     2016    Sunrisers Hyderabad
10    2018    Chennai Super Kings
11    2019         Mumbai Indians

In [38]:
#find win_by_runs margin and exclude where win_by_runs = 0
pd.value_counts(matches['win_by_runs']).head()

0     419
14     13
4      11
10     11
1      10
Name: win_by_runs, dtype: int64

In [42]:
temp_df = matches[matches['win_by_runs'] != 0]

In [47]:
pd.value_counts(temp_df['win_by_runs']).head()

14    13
10    11
4     11
1     10
13     9
Name: win_by_runs, dtype: int64

In [48]:
#find how many matches a team won in a season
seasons = pd.unique(matches['season'])

In [57]:
winners_in_each_season = []
for season in seasons:
    matches_in_a_season = matches[matches['season']==season]
    winners_in_each_season.append(pd.value_counts(matches_in_a_season['winner']))

In [61]:
for i in range(len(winners_in_each_season)):
    print(f'Season - {seasons[i]}')
    print(winners_in_each_season[i])
    print('\n')

Season - 2017
Mumbai Indians                 12
Rising Pune Supergiant         10
Kolkata Knight Riders           9
Sunrisers Hyderabad             8
Kings XI Punjab                 7
Delhi Daredevils                6
Gujarat Lions                   4
Royal Challengers Bangalore     3
Name: winner, dtype: int64


Season - 2008
Rajasthan Royals               13
Kings XI Punjab                10
Chennai Super Kings             9
Delhi Daredevils                7
Mumbai Indians                  7
Kolkata Knight Riders           6
Royal Challengers Bangalore     4
Deccan Chargers                 2
Name: winner, dtype: int64


Season - 2009
Delhi Daredevils               10
Deccan Chargers                 9
Royal Challengers Bangalore     9
Chennai Super Kings             8
Kings XI Punjab                 7
Rajasthan Royals                6
Mumbai Indians                  5
Kolkata Knight Riders           3
Name: winner, dtype: int64


Season - 2010
Mumbai Indians                 11
Chennai Super Kings             9
Deccan Chargers                 8
Royal Challengers Bangalore     8
Kolkata Knight Riders           7
Delhi Daredevils                7
Rajasthan Royals                6
Kings XI Punjab                 4
Name: winner, dtype: int64


Season - 2011
Chennai Super Kings            11
Mumbai Indians                 10
Royal Challengers Bangalore    10
Kolkata Knight Riders           8
Kings XI Punjab                 7
Kochi Tuskers Kerala            6
Rajasthan Royals                6
Deccan Chargers                 6
Delhi Daredevils                4
Pune Warriors                   4
Name: winner, dtype: int64


Season - 2012
Kolkata Knight Riders          12
Delhi Daredevils               11
Chennai Super Kings            10
Mumbai Indians                 10
Royal Challengers Bangalore     8
Kings XI Punjab                 8
Rajasthan Royals                7
Pune Warriors                   4
Deccan Chargers                 4
Name: winner, dtype: int64


Season - 2013
Mumbai Indians                 13
Chennai Super Kings            12
Rajasthan Royals               11
Sunrisers Hyderabad            10
Royal Challengers Bangalore     9
Kings XI Punjab                 8
Kolkata Knight Riders           6
Pune Warriors                   4
Delhi Daredevils                3
Name: winner, dtype: int64


Season - 2014
Kings XI Punjab                12
Kolkata Knight Riders          11
Chennai Super Kings            10
Rajasthan Royals                7
Mumbai Indians                  7
Sunrisers Hyderabad             6
Royal Challengers Bangalore     5
Delhi Daredevils                2
Name: winner, dtype: int64


Season - 2015
Chennai Super Kings            10
Mumbai Indians                 10
Royal Challengers Bangalore     8
Kolkata Knight Riders           7
Sunrisers Hyderabad             7
Rajasthan Royals                7
Delhi Daredevils                5
Kings XI Punjab                 3
Name: winner, dtype: int64


Season - 2016
Sunrisers Hyderabad            11
Royal Challengers Bangalore     9
Gujarat Lions                   9
Kolkata Knight Riders           8
Delhi Daredevils                7
Mumbai Indians                  7
Rising Pune Supergiants         5
Kings XI Punjab                 4
Name: winner, dtype: int64


Season - 2018
Chennai Super Kings            11
Sunrisers Hyderabad            10
Kolkata Knight Riders           9
Rajasthan Royals                7
Royal Challengers Bangalore     6
Kings XI Punjab                 6
Mumbai Indians                  6
Delhi Daredevils                5
Name: winner, dtype: int64


Season - 2019
Mumbai Indians                 11
Delhi Capitals                 10
Chennai Super Kings            10
Kolkata Knight Riders           6
Sunrisers Hyderabad             6
Kings XI Punjab                 6
Rajasthan Royals                5
Royal Challengers Bangalore     5
Name: winner, dtype: int64

In [62]:
seasons

array([2017, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2018,
       2019])

In [63]:
#find matches where CSK won by more than 50 runs
#Print three columns - team1, team2, win_by_runs margin
matches[(first condition) & (second condition)]

In [64]:
#1. find 5 players who took most number of catches
#2. find 5 players with most wickets
#3. find the player who was given out max. no of times
#by the following way - 
# .    - caught
# .    - bowled
# .    - run out
# .    - lbw
# .    - caught and bowled
# .    - stumped
# .    - hit wicket
# .    - obstructing the field

In [70]:
deliveries = pd.read_csv('deliveries.csv')

In [71]:
pd.unique(deliveries['dismissal_kind'])

array([nan, 'caught', 'bowled', 'run out', 'lbw', 'caught and bowled',
       'stumped', 'retired hurt', 'hit wicket', 'obstructing the field'],
      dtype=object)

In [72]:
deliveries.columns

Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batsman', 'non_striker', 'bowler', 'is_super_over', 'wide_runs',
       'bye_runs', 'legbye_runs', 'noball_runs', 'penalty_runs',
       'batsman_runs', 'extra_runs', 'total_runs', 'player_dismissed',
       'dismissal_kind', 'fielder'],
      dtype='object')

In [73]:
deliveries.shape

(179078, 21)